; platformio.ini
; Generic ESP32 configuration for PlatformIO

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor
monitor_speed = 115200
upload_speed = 921600

; Build options
build_flags =
    -DCORE_DEBUG_LEVEL=3

lib_deps = fastled/FastLED@^3.10.3


